### ISSUE TITLE
instance id used instead of EIP ENI

### ISSUE THREAD

**Issue by ralph-tice** [hectcastro/terraform-aws-vpc#1]
https://github.com/hectcastro/terraform-aws-vpc/blob/develop/aws-vpc.tf#L113 should use network_interface_id
https://www.terraform.io/docs/providers/aws/r/route_table.html#network_interface_id

**Comment by ralph-tice** [comment]
I mistakenly thought this was creating a separate ENI, which it isn't, so this doesn't matter, strictly speaking.  However, if you did create a separate ENI, you wouldn't have to update route tables on instance failures/rotations.  For my use case I added autorecovery alarms.  I have a gist up at https://gist.github.com/ralph-tice/3d6e5b2076cbc2900aaa that demonstrates this.

**Comment by hectcastro** [comment]
All good. Thanks for the information. I opened https://github.com/hectcastro/terraform-aws-vpc/issues/2 to add auto recovery support.
